Module message: Setting OPENBLAS_NUM_THREADS to 1. Done. 
Tree distance on sample: 71
Tree distance on sample: 78
Already done 78
Tree distance on sample: 30
Tree distance on sample: 41
Tree distance on sample: 87
Already done 87
Already done 41
Tree distance on sample: 106
Already done 106
Tree distance on sample: 111
Tree distance on sample: 66
Already done 66
Tree distance on sample: 95
Tree distance on sample: 47
Tree distance on sample: 69
Already done 69
Tree distance on sample: 89
Tree distance on sample: 127
Already done 127
Tree distance on sample: 21
Tree distance on sample: 18
Tree distance on sample: 40
Already done 40
Tree distance on sample: 60
Already done 60
Tree distance on sample: 91
Tree distance on sample: 201
Tree distance on sample: 118
Tree distance on sample: 38
Already done 38
Tree distance on sample: 70
Tree distance on sample: 75
Tree distance on sample: 10
Tree distance on sample: 76
Tree distance on sample: 8
Tree distance on sample: 12
Tree distance on sample: 6
Tree distance on sample: 14
Already done 14
Tree distance on sample: 131
Already done 131
Tree distance on sample: 84
Already done 84
Tree distance on sample: 53
Tree distance on sample: 104
Tree distance on sample: 112
Already done 112
Tree distance on sample: 35
Already done 35
Tree distance on sample: 9
Tree distance on sample: 94
Already done 94
Tree distance on sample: 122
Already done 122
Tree distance on sample: 19
Already done 19
Tree distance on sample: 16
Tree distance on sample: 51
Tree distance on sample: 39
Tree distance on sample: 67
Tree distance on sample: 229
Already done 229
Tree distance on sample: 83
Tree distance on sample: 45
Already done 45
Tree distance on sample: 109
Tree distance on sample: 88
Tree distance on sample: 37
Tree distance on sample: 23
Tree distance on sample: 153
Tree distance on sample: 120
Tree distance on sample: 50
Tree distance on sample: 114
Tree distance on sample: 80
Tree distance on sample: 146
Tree distance on sample: 25
Tree distance on sample: 27
Tree distance on sample: 82
Already done 82
Tree distance on sample: 119
Already done 119
Tree distance on sample: 57
Already done 57
Tree distance on sample: 20
Tree distance on sample: 29
Tree distance on sample: 107
Tree distance on sample: 81
Tree distance on sample: 243
Tree distance on sample: 149
Already done 149
Tree distance on sample: 15
Tree distance on sample: 121
Tree distance on sample: 79
Already done 79
Tree distance on sample: 90
Tree distance on sample: 72
Already done 72
Tree distance on sample: 152
Tree distance on sample: 59
Tree distance on sample: 142
Already done 59
Tree distance on sample: 200
Tree distance on sample: 110
Already done 110
Tree distance on sample: 11
Already done 11
Tree distance on sample: 73
Already done 73
Tree distance on sample: 188
Tree distance on sample: 108
Already done 108
Tree distance on sample: 147
Tree distance on sample: 97
Tree distance on sample: 148
Tree distance on sample: 52
Tree distance on sample: 63
Already done 63
Tree distance on sample: 193
Tree distance on sample: 123
Tree distance on sample: 93
Tree distance on sample: 139
Tree distance on sample: 4
Tree distance on sample: 31
Tree distance on sample: 157
Already done 157
Tree distance on sample: 165
Tree distance on sample: 135
Tree distance on sample: 26
Already done 26
Tree distance on sample: 86
Tree distance on sample: 168
Already done 168
Tree distance on sample: 43
Already done 43
Tree distance on sample: 17
Already done 17
Tree distance on sample: 141
Already done 141
Tree distance on sample: 169
Tree distance on sample: 237
Tree distance on sample: 64
Tree distance on sample: 101
Tree distance on sample: 103
Tree distance on sample: 42
Already done 42
Tree distance on sample: 140
Tree distance on sample: 145
Tree distance on sample: 144
Tree distance on sample: 33
Tree distance on sample: 68
Tree distance on sample: 125
Tree distance on sample: 36
Tree distance on sample: 216
Tree distance on sample: 56
Already done 56
Tree distance on sample: 136
Tree distance on sample: 133
Tree distance on sample: 137
Already done 137
Tree distance on sample: 13
Tree distance on sample: 115
Tree distance on sample: 225
Tree distance on sample: 22
Tree distance on sample: 48
Tree distance on sample: 176
Tree distance on sample: 170
Tree distance on sample: 219
Tree distance on sample: 65
Tree distance on sample: 232
Tree distance on sample: 183
Already done 183
Tree distance on sample: 212
Already done 212
Tree distance on sample: 164
Already done 164
Tree distance on sample: 61
Already done 61
Tree distance on sample: 189
Tree distance on sample: 172
Already done 172
Tree distance on sample: 162
Tree distance on sample: 241
Tree distance on sample: 100
Tree distance on sample: 166
Tree distance on sample: 105
Tree distance on sample: 220
Tree distance on sample: 98
Tree distance on sample: 210
Tree distance on sample: 240
Tree distance on sample: 74
Tree distance on sample: 223
Tree distance on sample: 3
Tree distance on sample: 1
Tree distance on sample: 196
Tree distance on sample: 178
Tree distance on sample: 167
Tree distance on sample: 134
Tree distance on sample: 58
Tree distance on sample: 126
Tree distance on sample: 92
Tree distance on sample: 182
Tree distance on sample: 214
Tree distance on sample: 155
Already done 155
Tree distance on sample: 181
Tree distance on sample: 242
Tree distance on sample: 32
Tree distance on sample: 187
Already done 187
Tree distance on sample: 198
Tree distance on sample: 99
Already done 99
Tree distance on sample: 28
Tree distance on sample: 250
Already done 250
Tree distance on sample: 96
Tree distance on sample: 239
Already done 239
Tree distance on sample: 116
Tree distance on sample: 49
Tree distance on sample: 227
Tree distance on sample: 226
Tree distance on sample: 238
Tree distance on sample: 46
Tree distance on sample: 230
Tree distance on sample: 124
Already done 124
Tree distance on sample: 199
Tree distance on sample: 129
Already done 129
Tree distance on sample: 194
Tree distance on sample: 113
Tree distance on sample: 163
Tree distance on sample: 24
Tree distance on sample: 247
Tree distance on sample: 195
Tree distance on sample: 143
Tree distance on sample: 2
Already done 143
Tree distance on sample: 151
Tree distance on sample: 209
Already done 151
Tree distance on sample: 205
Tree distance on sample: 102
Tree distance on sample: 150
Tree distance on sample: 158
Tree distance on sample: 207
Tree distance on sample: 213
Tree distance on sample: 160
Already done 160
Tree distance on sample: 175
Tree distance on sample: 180
Tree distance on sample: 130
Tree distance on sample: 55
Already done 55
Tree distance on sample: 154
Tree distance on sample: 156
Tree distance on sample: 192
Already done 192
Tree distance on sample: 233
Tree distance on sample: 186
Tree distance on sample: 44
Tree distance on sample: 7
Tree distance on sample: 206
Tree distance on sample: 190
Tree distance on sample: 246
Tree distance on sample: 54
Tree distance on sample: 208
Already done 208
Tree distance on sample: 128
Tree distance on sample: 235
Tree distance on sample: 171
Already done 171
Tree distance on sample: 244
Tree distance on sample: 34
Tree distance on sample: 77
Tree distance on sample: 85
Tree distance on sample: 231
Already done 231
Tree distance on sample: 174
Tree distance on sample: 249
Tree distance on sample: 5
Tree distance on sample: 161
Tree distance on sample: 215
Tree distance on sample: 228
Already done 228
Tree distance on sample: 234
Tree distance on sample: 204
Tree distance on sample: 117
Already done 117
Tree distance on sample: 185
Tree distance on sample: 211
Tree distance on sample: 197
Tree distance on sample: 224
Already done 224
Tree distance on sample: 236
Tree distance on sample: 132
Tree distance on sample: 138
Tree distance on sample: 184
Tree distance on sample: 217
Already done 217
Tree distance on sample: 203
Already done 203
Tree distance on sample: 222
Tree distance on sample: 221
Already done 221
Tree distance on sample: 218
Tree distance on sample: 159
Tree distance on sample: 179
Tree distance on sample: 177
Tree distance on sample: 248
Tree distance on sample: 191
Tree distance on sample: 202
Tree distance on sample: 245
Tree distance on sample: 173
Already done 173
Tree distance on sample: 62
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    return _read(filepath_or_buffer, kwds)
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
OSError: [Errno 12] Cannot allocate memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Distance of 1.3835925294425881
Distance of 1.2496605179261122
Distance of 1.1675757658410435
Distance of 1.088333335562683
Distance of 1.3989503667512504
Distance of 1.022170203530639
Distance of 1.1106669707609795
Distance of 1.1406993948338902
Distance of 1.020847562067834
Distance of 1.1396933797584963
Distance of 0.9964564756920933
Distance of 1.5312809481068026
Distance of 1.2357576981510885
Distance of 1.0540695684831225
Distance of 1.1054266814942717
Distance of 0.7440941817997351
Distance of 0.9140641375924907
Distance of 0.9885714863982701
Distance of 0.9576495552701122
Distance of 0.9969255763832322
Distance of 0.9575239089063035
Distance of 0.9578009518376669
Distance of 0.8046592864874133
Distance of 0.972414446400931
Distance of 0.8897678213755449
Distance of 0.9395169111737336
Distance of 0.8961885424189222
Distance of 1.0489345174678637
Distance of 0.9679308360185468
Distance of 1.0374070282958474
Distance of 0.9958798179241798
Distance of 0.7989084173149611
Distance of 0.9840620198864908
Distance of 0.9611229515110792
Distance of 0.9460844392202012
Distance of 0.9056221024425614
Distance of 0.9469765455892281
Distance of 0.9523905232452924
Distance of 0.9267457719944645
Distance of 1.0319068492241648
Distance of 0.907033161035892
Distance of 0.8283289819687922
Distance of 0.762930300975784
Distance of 0.8900645036803966
Distance of 0.5837482617419736
Distance of 0.9990728876061734
Distance of 1.0868602998294754
Distance of 0.6760147822233372
Distance of 0.9244713395004907
Distance of 0.8866853684208756
Distance of 0.650715968687842
Distance of 0.5548981739159389
Distance of 0.8563783741460267
Distance of 0.6657504896960971
Distance of 0.4978964949307762
Distance of 0.49673737819087294
slurmstepd: error: Detected 106463 oom-kill event(s) in step 7708746.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
