Module message: Setting OPENBLAS_NUM_THREADS to 1. Done. 
Tree distance on sample: 114
Tree distance on sample: 60
Already done 60
Tree distance on sample: 79
Already done 79
Tree distance on sample: 14
Already done 14
Tree distance on sample: 72
Already done 72
Tree distance on sample: 38
Already done 38
Tree distance on sample: 3
Tree distance on sample: 1
Tree distance on sample: 145
Tree distance on sample: 179
Tree distance on sample: 112
Already done 112
Tree distance on sample: 22
Tree distance on sample: 26
Already done 26
Tree distance on sample: 88
Tree distance on sample: 130
Tree distance on sample: 152
Tree distance on sample: 57
Already done 57
Tree distance on sample: 171
Already done 171
Tree distance on sample: 109
Tree distance on sample: 186
Tree distance on sample: 70
Tree distance on sample: 89
Tree distance on sample: 123
Tree distance on sample: 185
Tree distance on sample: 12
Tree distance on sample: 108
Tree distance on sample: 165
Already done 108
Tree distance on sample: 149
Already done 149
Tree distance on sample: 75
Tree distance on sample: 161
Tree distance on sample: 164
Already done 164
Tree distance on sample: 47
Tree distance on sample: 46
Tree distance on sample: 27
Tree distance on sample: 2
Tree distance on sample: 81
Tree distance on sample: 133
Tree distance on sample: 141
Already done 141
Tree distance on sample: 233
Tree distance on sample: 86
Tree distance on sample: 31
Tree distance on sample: 159
Tree distance on sample: 62
Tree distance on sample: 24
Tree distance on sample: 74
Tree distance on sample: 137
Already done 137
Tree distance on sample: 59
Already done 59
Tree distance on sample: 43
Already done 43
Tree distance on sample: 115
Tree distance on sample: 36
Tree distance on sample: 39
Tree distance on sample: 21
Tree distance on sample: 10
Tree distance on sample: 61
Already done 61
Tree distance on sample: 32
Tree distance on sample: 144
Tree distance on sample: 15
Tree distance on sample: 242
Tree distance on sample: 67
Tree distance on sample: 127
Already done 127
Tree distance on sample: 125
Tree distance on sample: 237
Tree distance on sample: 34
Tree distance on sample: 214
Tree distance on sample: 65
Tree distance on sample: 58
Tree distance on sample: 104
Tree distance on sample: 33
Tree distance on sample: 136
Tree distance on sample: 78
Already done 78
Tree distance on sample: 97
Tree distance on sample: 30
Tree distance on sample: 129
Already done 129
Tree distance on sample: 71
Tree distance on sample: 105
Tree distance on sample: 7
Tree distance on sample: 138
Tree distance on sample: 64
Tree distance on sample: 117
Already done 117
Tree distance on sample: 8
Tree distance on sample: 175
Tree distance on sample: 83
Tree distance on sample: 95
Tree distance on sample: 119
Already done 119
Tree distance on sample: 124
Already done 124
Tree distance on sample: 100
Tree distance on sample: 143
Already done 143
Tree distance on sample: 6
Tree distance on sample: 121
Tree distance on sample: 17
Already done 17
Tree distance on sample: 170
Tree distance on sample: 11
Already done 11
Tree distance on sample: 120
Tree distance on sample: 150
Tree distance on sample: 20
Tree distance on sample: 99
Already done 99
Tree distance on sample: 41
Already done 41
Tree distance on sample: 73
Already done 73
Tree distance on sample: 102
Tree distance on sample: 48
Tree distance on sample: 53
Tree distance on sample: 122
Already done 122
Tree distance on sample: 42
Already done 42
Tree distance on sample: 107
Tree distance on sample: 68
Tree distance on sample: 80
Tree distance on sample: 167
Tree distance on sample: 134
Tree distance on sample: 18
Tree distance on sample: 49
Tree distance on sample: 148
Tree distance on sample: 55
Already done 55
Tree distance on sample: 94
Already done 94
Tree distance on sample: 160
Already done 160
Tree distance on sample: 82
Already done 82
Tree distance on sample: 147
Tree distance on sample: 40
Already done 40
Tree distance on sample: 218
Tree distance on sample: 13
Tree distance on sample: 192
Already done 192
Tree distance on sample: 157
Already done 157
Tree distance on sample: 76
Tree distance on sample: 111
Tree distance on sample: 98
Tree distance on sample: 84
Already done 84
Tree distance on sample: 220
Tree distance on sample: 29
Tree distance on sample: 51
Tree distance on sample: 204
Tree distance on sample: 118
Tree distance on sample: 158
Tree distance on sample: 222
Tree distance on sample: 116
Tree distance on sample: 217
Already done 217
Tree distance on sample: 142
Tree distance on sample: 153
Tree distance on sample: 208
Already done 208
Tree distance on sample: 219
Tree distance on sample: 169
Tree distance on sample: 162
Tree distance on sample: 172
Already done 172
Tree distance on sample: 245
Tree distance on sample: 195
Tree distance on sample: 239
Already done 239
Tree distance on sample: 176
Tree distance on sample: 193
Tree distance on sample: 221
Already done 221
Tree distance on sample: 196
Tree distance on sample: 209
Tree distance on sample: 16
Tree distance on sample: 93
Tree distance on sample: 103
Tree distance on sample: 154
Tree distance on sample: 173
Already done 173
Tree distance on sample: 183
Already done 183
Tree distance on sample: 106
Already done 106
Tree distance on sample: 199
Tree distance on sample: 184
Tree distance on sample: 211
Tree distance on sample: 213
Tree distance on sample: 156
Tree distance on sample: 52
Tree distance on sample: 101
Tree distance on sample: 45
Already done 45
Tree distance on sample: 205
Tree distance on sample: 131
Already done 131
Tree distance on sample: 25
Tree distance on sample: 126
Tree distance on sample: 96
Tree distance on sample: 174
Tree distance on sample: 135
Tree distance on sample: 203
Tree distance on sample: 229
Already done 229
Already done 203
Tree distance on sample: 238
Tree distance on sample: 202
Tree distance on sample: 210
Tree distance on sample: 50
Tree distance on sample: 230
Tree distance on sample: 206
Tree distance on sample: 224
Already done 224
Tree distance on sample: 200
Tree distance on sample: 223
Tree distance on sample: 163
Tree distance on sample: 235
Tree distance on sample: 181
Tree distance on sample: 140
Tree distance on sample: 77
Tree distance on sample: 166
Tree distance on sample: 234
Tree distance on sample: 197
Tree distance on sample: 232
Tree distance on sample: 227
Tree distance on sample: 110
Already done 110
Tree distance on sample: 250
Tree distance on sample: 189
Already done 250
Tree distance on sample: 69
Already done 69
Tree distance on sample: 182
Tree distance on sample: 177
Tree distance on sample: 243
Tree distance on sample: 28
Tree distance on sample: 226
Tree distance on sample: 190
Tree distance on sample: 168
Already done 168
Tree distance on sample: 231
Already done 231
Tree distance on sample: 215
Tree distance on sample: 207
Tree distance on sample: 155
Already done 155
Tree distance on sample: 44
Tree distance on sample: 225
Tree distance on sample: 187
Already done 187
Tree distance on sample: 66
Already done 66
Tree distance on sample: 201
Tree distance on sample: 128
Tree distance on sample: 91
Tree distance on sample: 247
Tree distance on sample: 23
Tree distance on sample: 146
Tree distance on sample: 90
Tree distance on sample: 113
Tree distance on sample: 180
Tree distance on sample: 87
Already done 87
Tree distance on sample: 19
Tree distance on sample: 35
Already done 35
Already done 19
Tree distance on sample: 198
Tree distance on sample: 132
Tree distance on sample: 194
Tree distance on sample: 92
Tree distance on sample: 151
Already done 151
Tree distance on sample: 37
Tree distance on sample: 54
Tree distance on sample: 9
Tree distance on sample: 4
Tree distance on sample: 212
Tree distance on sample: 5
Already done 212
Tree distance on sample: 216
Tree distance on sample: 228
Already done 228
Tree distance on sample: 246
Tree distance on sample: 63
Already done 63
Tree distance on sample: 85
Tree distance on sample: 188
Tree distance on sample: 139
Tree distance on sample: 249
Tree distance on sample: 178
Tree distance on sample: 244
Tree distance on sample: 241
Tree distance on sample: 236
Tree distance on sample: 248
Tree distance on sample: 56
Already done 56
Tree distance on sample: 240
Tree distance on sample: 191
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
Traceback (most recent call last):
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
Traceback (most recent call last):
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
Traceback (most recent call last):
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
OSError: [Errno 12] Cannot allocate memory
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
OSError: [Errno 12] Cannot allocate memory
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
Traceback (most recent call last):
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
OSError: [Errno 12] Cannot allocate memory
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
OSError: [Errno 12] Cannot allocate memory
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
Traceback (most recent call last):
OSError: [Errno 12] Cannot allocate memory
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
Traceback (most recent call last):
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
Traceback (most recent call last):
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
Traceback (most recent call last):
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
OSError: [Errno 12] Cannot allocate memory
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
OSError: [Errno 12] Cannot allocate memory
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
OSError: [Errno 12] Cannot allocate memory
OSError: [Errno 12] Cannot allocate memory
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
Traceback (most recent call last):
OSError: [Errno 12] Cannot allocate memory
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
OSError: [Errno 12] Cannot allocate memory
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
OSError: [Errno 12] Cannot allocate memory
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
OSError: [Errno 12] Cannot allocate memory
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
    return _read(filepath_or_buffer, kwds)
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
OSError: [Errno 12] Cannot allocate memory
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
OSError: [Errno 12] Cannot allocate memory
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
Traceback (most recent call last):
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
OSError: [Errno 12] Cannot allocate memory
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
OSError: [Errno 12] Cannot allocate memory
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
OSError: [Errno 12] Cannot allocate memory
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
OSError: [Errno 12] Cannot allocate memory
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 26, in <module>
    df = pd.read_csv("data/Tidy_Topics/tidy_topics_str.csv")
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
IndexError: list index out of range
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 84, in <module>
    d = total_dist(full_data, sample_data)
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 40, in total_dist
    max_depth_sample = len(list(sample_data.items())[1][1][0].split("-"))
IndexError: list index out of range
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[9542,0],0] on node r24-n1
  Remote daemon: [[9542,0],1] on node r24-n2

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
slurmstepd: error: *** JOB 7708740 ON r24-n1 CANCELLED AT 2021-06-23T06:16:41 DUE TO TIME LIMIT ***
slurmstepd: error: Detected 715568 oom-kill event(s) in step 7708740.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
