Tree distance on sample: 1632
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_tree_dist.py", line 28, in <module>
    Vocab_samp = pd.read_csv("data/Vocab/sample_"+str(sample)+".csv")[['word_ID_full', 'freq']].set_index('word_ID_full').T.to_dict('list')
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/Vocab/sample_1632.csv'
