Module message: Setting OPENBLAS_NUM_THREADS to 1. Done. 
[warn] poll: Bad address
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 1, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 3, in <module>
    import matplotlib
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 174, in <module>
    _check_versions()
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: /hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/../../../libstdc++.so.6: cannot read file data: Cannot allocate memory
    import pylab as plt
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/pylab.py", line 18, in <module>
    from matplotlib.dates import (
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/dates.py", line 161, in <module>
    import dateutil.parser
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/dateutil/parser/__init__.py", line 2, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 3, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 50, in <module>
    from .. import tz
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/dateutil/tz/tz.py", line 22, in <module>
    from ._common import tzname_in_python2, _tzinfo
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 980, in get_data
OSError: [Errno 12] Cannot allocate memory
    import pylab as plt
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pylab.py", line 1, in <module>
/apps/skl/software/R/4.0.3/lib64/R/bin/BATCH: line 60: 114914 Killed                  ${R_HOME}/bin/R -f ${in} ${opts} ${R_BATCH_OPTIONS} > ${out} 2>&1
    from matplotlib.pylab import *
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/pylab.py", line 18, in <module>
    from matplotlib.dates import (
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/dates.py", line 161, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 1, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 3, in <module>
    import matplotlib
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 107, in <module>
    import pylab as plt
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pylab.py", line 1, in <module>
    from . import cbook, rcsetup
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 28, in <module>
    import numpy as np
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/numpy/__init__.py", line 154, in <module>
    from matplotlib.pylab import *
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/pylab.py", line 18, in <module>
    from . import fft
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 980, in get_data
OSError: [Errno 12] Cannot allocate memory
    from matplotlib.dates import (
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/dates.py", line 157, in <module>
    from dateutil.rrule import (rrule, MO, TU, WE, TH, FR, SA, SU, YEARLY,
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/dateutil/rrule.py", line 23, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 1, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 1, in <module>
    import matplotlib
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import cbook, rcsetup
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 28, in <module>
    import matplotlib
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 3, in <module>
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 174, in <module>
    import pylab as plt
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pylab.py", line 1, in <module>
    _check_versions()
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 159, in _check_versions
    from . import ft2font
    from matplotlib.pylab import *
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/pylab.py", line 18, in <module>
ImportError: /hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/../../../libfreetype.so.6: cannot read file data: Cannot allocate memory
    from matplotlib.dates import (
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/dates.py", line 157, in <module>
    from dateutil.rrule import (rrule, MO, TU, WE, TH, FR, SA, SU, YEARLY,
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/dateutil/rrule.py", line 10, in <module>
    import calendar
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 980, in get_data
OSError: [Errno 12] Cannot allocate memory
/apps/skl/software/R/4.0.3/lib64/R/bin/BATCH: line 60: 137024 Killed                  ${R_HOME}/bin/R -f ${in} ${opts} ${R_BATCH_OPTIONS} > ${out} 2>&1
./my_program.sh: line 16: /hpcfs/users/a1670295/myconda/envs/gt/bin/python3.9: Argument list too long
./my_program.sh: line 16: /hpcfs/users/a1670295/myconda/envs/gt/bin/python3.9: Argument list too long
./my_program.sh: line 16: /hpcfs/users/a1670295/myconda/envs/gt/bin/python3.9: Argument list too long
./my_program.sh: line 16: /hpcfs/users/a1670295/myconda/envs/gt/bin/python3.9: Argument list too long
./my_program.sh: line 16: /hpcfs/users/a1670295/myconda/envs/gt/bin/python3.9: Argument list too long
./my_program.sh: line 16: /hpcfs/users/a1670295/myconda/envs/gt/bin/python3.9: Bad address
./my_program.sh: line 16: /hpcfs/users/a1670295/myconda/envs/gt/bin/python3.9: Argument list too long
./my_program.sh: line 16: /hpcfs/users/a1670295/myconda/envs/gt/bin/python3.9: Argument list too long
./my_program.sh: line 16: /hpcfs/users/a1670295/myconda/envs/gt/bin/python3.9: Argument list too long
    import numpy as np
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/numpy/__init__.py", line 155, in <module>
    from . import polynomial
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/numpy/polynomial/__init__.py", line 117, in <module>
    from .polynomial import Polynomial
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1349, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1321, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1450, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1490, in _fill_cache
OSError: [Errno 12] Cannot allocate memory: '/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/numpy/polynomial'
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 1, in <module>
    import matplotlib
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 913, in <module>
    rcParamsDefault = _rc_params_in_file(
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 814, in _rc_params_in_file
    for line_no, line in enumerate(fd, 1):
OSError: [Errno 12] Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 1, in <module>
    import matplotlib
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 174, in <module>
    _check_versions()
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 168, in _check_versions
    module = importlib.import_module(modname)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/kiwisolver.cpython-39-x86_64-linux-gnu.so: cannot read file data: Cannot allocate memory
[r24-gpu1:113345] PMIX ERROR: BAD-PARAM in file event/pmix_event_notification.c at line 923
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 3, in <module>
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 1, in <module>
    import pylab as plt
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/pylab.py", line 18, in <module>
    from matplotlib.dates import (
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/dates.py", line 168, in <module>
    import matplotlib.ticker as ticker
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    import matplotlib
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 174, in <module>
    _check_versions()
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: /hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/../../.././libpng16.so.16: cannot read file data: Cannot allocate memory
Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 1, in <module>
    import matplotlib
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 921, in <module>
    dict.update(rcParams, _rc_params_in_file(matplotlib_fname()))
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/matplotlib/__init__.py", line 814, in _rc_params_in_file
    for line_no, line in enumerate(fd, 1):
OSError: [Errno 12] Cannot allocate memory
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 980, in get_data
OSError: [Errno 12] Cannot allocate memory
slurmstepd: error: Detected 1669 oom-kill event(s) in step 6534780.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
#
#===========================================================================
#HPC1 Job Utilisation Reporting
===========================================================================
Job Name            : script.sh
Job ID              : 6534780
User                : a1670295
Account             : mathsci
Cluster             : hpc1
Partition           : v100cpu
Nodes (List)        : 1,2 (r24-gpu[1-2])
Cores               : 4
GPUs                : 0
State               : CANCELLED,OUT_OF_MEMORY
Submit              : 2021-06-10T23:02:56
Start               : 2021-06-10T23:04:28
End                 : 2021-06-10T23:17:03
Walltime reserved   : 01:00:00
Walltime elapsed (%): 00:12:35  (21.0% * reserved)
CPU-time elapsed    : 0.84 core-hours
% CPU used (Total)  :  0.42%    (0.00 core-hours)
% User CPU (Compute):  0.19%    (0.00 core-hours)
% System CPU (I/O)  :  0.24%    (0.00 core-hours)
Mem reserved        : 4G/node
% Mem used (Max)    : 119.79%    (4.79G/node) 
Max Disk Write      : 1.47M     (,r24-gpu1)
Max Disk Read       : 1.02G     (,r24-gpu1)
===========================================================================
