Traceback (most recent call last):
  File "/hpcfs/users/a1670295/Sampling/Python/phoenix_hSBM.py", line 18, in <module>
    sample_prop = sample_info.query("sample == @sample")['sample_prop'].iloc[0]
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/core/indexing.py", line 1501, in _getitem_axis
    self._validate_integer(key, axis)
  File "/hpcfs/users/a1670295/myconda/envs/gt/lib/python3.9/site-packages/pandas/core/indexing.py", line 1444, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
slurmstepd: error: *** JOB 8466823 ON r25-n2 CANCELLED AT 2021-07-02T00:23:35 ***
